
defaults: &defaults
  working_directory: ~/gatsby-otilio-starter
  docker:
    - image: circleci/node:8.9-stretch
      environment:
          TZ: "/usr/share/zoneinfo/Europe/Warsaw"
  environment:
      TZ: "/usr/share/zoneinfo/Europe/Warsaw"

whitelist: &whitelist
  paths:
    - .git/
    - data/
    - posts/
    - flow-typed/
    - internals/
    - node_modules/
    - src/
    - tests/
    - static/
    - .babelrc
    - .eslintignore
    - .eslintrc.js
    - .flowconfig
    - .flowcoverage.json
    - .stylelintrc
    - .gitignore
    - package.json
    - yarn.lock
    - gatsby-config.js
    - gatsby-node.js
    - config.js
    - config.yml

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache--{{ checksum "package.json" }}
          - dependency-cache--
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache--{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/gatsby-otilio-starter
          <<: *whitelist
  flow_typed:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/gatsby-otilio-starter
      - run:
          name: Flow Typed
          command: yarn flow:typed
      - persist_to_workspace:
          root: ~/gatsby-otilio-starter
          <<: *whitelist
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/gatsby-otilio-starter
      - run:
          name: Eslint check
          command: yarn lint
  flow:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/gatsby-otilio-starter
      - run:
          name: Flow check
          command: yarn flow
      - run:
          name: Flow coverage
          command: yarn flow:coverage
  stylelint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/gatsby-otilio-starter
      - run:
          name: Stylelint check
          command: yarn lint:styles
  test:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/gatsby-otilio-starter
    - run:
        name: Test
        command: yarn test
  build:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/gatsby-otilio-starter
    - run:
        name: Build
        command: yarn build
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - flow_typed:
          requires:
            - checkout
      - lint:
          requires:
            - flow_typed
      - flow:
          requires:
            - flow_typed
      - stylelint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - checkout
